-- klasicni insertovi
INSERT INTO zav_profesori(ime, prezime) VALUES ('Viseslav','Knezovic');
INSERT INTO zav_profesori(ime, prezime) VALUES ('Mirna','Andric');
INSERT INTO zav_profesori(ime, prezime) VALUES ('Zvonko','Jakovljevic');
INSERT INTO zav_profesori(ime, prezime) VALUES ('Pavao','Simic');
INSERT INTO zav_profesori(ime, prezime) VALUES ('Elena','Pavlic');
INSERT INTO zav_profesori(ime, prezime) VALUES ('Vana','Pavkovic');
INSERT INTO zav_profesori(ime, prezime) VALUES ('Gracijan','Boskovic');
INSERT INTO zav_profesori(ime, prezime) VALUES ('Leopold','Matanovic');
INSERT INTO zav_profesori(ime, prezime) VALUES ('Lazar','Bosnjak');
INSERT INTO zav_profesori(ime, prezime) VALUES ('Ana','Sever');

INSERT INTO zav_studenti(ime, prezime) VALUES ('Milivoj','Posavec');
INSERT INTO zav_studenti(ime, prezime) VALUES ('Nedjeljko','Kujundžic');
INSERT INTO zav_studenti(ime, prezime) VALUES ('Vinko','Vinkovic');
INSERT INTO zav_studenti(ime, prezime) VALUES ('Cvjeta','Martinovic');
INSERT INTO zav_studenti(ime, prezime) VALUES ('Anastazija','Sekulic');
INSERT INTO zav_studenti(ime, prezime) VALUES ('Tanja','Golubic');
INSERT INTO zav_studenti(ime, prezime) VALUES ('Ilija','Valentic');
INSERT INTO zav_studenti(ime, prezime) VALUES ('Leonarda','Peric');
INSERT INTO zav_studenti(ime, prezime) VALUES ('Ina','Lukic');
INSERT INTO zav_studenti(ime, prezime) VALUES ('Davor','Ivancic');


--jedan korisnik moze biti samo student ili profesor, ne oboje
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('mposavec','koliko99',1,NULL);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('nkujundzic','koliko99',2,NULL);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('vvinkovic','koliko99',3,NULL);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('cmartinovic','koliko99',4,NULL);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('asekulic','koliko99',5,NULL);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('tgolubic','koliko99',6,NULL);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('ivalentic','koliko99',7,NULL);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('lperic','koliko99',8,NULL);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('ilukic','koliko99',9,NULL);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('divancic','koliko99',10,NULL);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('vknezovic','koliko99',NULL,1);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('mandric','koliko99',NULL,2);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('zjakovljevic','koliko99',NULL,3);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('psimic','koliko99',NULL,4);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('epavlovic','koliko99',NULL,5);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('vpavkovic','koliko99',NULL,6);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('gboskovic','koliko99',NULL,7);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('lmatanovic','koliko99',NULL,8);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('lbosnjak','koliko99',NULL,9);
INSERT INTO zav_login(korIme,lozinka,studentID,profesorID) VALUES ('asever','koliko99',NULL,10);

INSERT INTO zav_predmeti(ime,profesorID) VALUES ('Uvod u Programiranje',1);
INSERT INTO zav_predmeti(ime,profesorID) VALUES ('Uvod u Govor',2);
INSERT INTO zav_predmeti(ime,profesorID) VALUES ('Napredne Tehnike Disanja',3);
INSERT INTO zav_predmeti(ime,profesorID) VALUES ('Osnove Samoobrane',4);
INSERT INTO zav_predmeti(ime,profesorID) VALUES ('Osnove Napada',5);
INSERT INTO zav_predmeti(ime,profesorID) VALUES ('Android Aplikacije',6);
INSERT INTO zav_predmeti(ime,profesorID) VALUES ('Psihicko Zdravlje I Ja',7);
INSERT INTO zav_predmeti(ime,profesorID) VALUES ('Java Programiranje',8);
INSERT INTO zav_predmeti(ime,profesorID) VALUES ('Kako znati kada prestati',9);
INSERT INTO zav_predmeti(ime,profesorID) VALUES ('Poljoprivreda',10);

INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Pisanje Koda',1);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Petlje',1);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Tipovi Podataka',1);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Stilovi govora',2);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Pasivno agresivan govorni stil',2);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Aktivno agresivan govorni stil',2);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Maksimiziranje SpO2',3);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Minimiziranje Gusenja',3);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('O2 kanistri',3);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Smirivanje rijecima',4);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Jiu Jitsu',4);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Sokeri',4);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Kako se prisuljati',5);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Srednjovjekovna oružja',5);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Kloroform',5);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('UI',6);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Logika',6);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Deprecated API',6);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Najbolje tablete za smirenje',7);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Samopostivanje',7);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Prepoznavanje psihicke nestabilnosti',7);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Petlje',8);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('WindowBuilder',8);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Web Applet',8);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Ovisnosti',9);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Alkoholizam',9);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Java Programiranje',9);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Gnojivo',10);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Plodored',10);
INSERT INTO zav_ishodi(ime,predmetID) VALUES ('Održivost',10);


--ishodiPolozeni rade na principu da ako je student upisan na neki predmet
--ubacujemo studenta u tablicu ishodi polozeni
--zajedno s svim ishodima tog predmeta

--kod dodavanja ishoda retroaktivno ubacujemo taj ishod svim studentima tog predmeta
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (1,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (2,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (3,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (4,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (5,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (6,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (7,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (8,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (9,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (10,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (11,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (12,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (13,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (14,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (15,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (16,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (17,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (18,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (19,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (20,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (21,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (22,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (23,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (24,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (25,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (26,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (27,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (28,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (29,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (30,1,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (1,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (2,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (3,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (4,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (5,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (6,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (7,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (8,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (9,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (10,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (11,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (12,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (13,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (14,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (15,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (16,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (17,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (18,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (19,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (20,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (21,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (22,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (23,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (24,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (25,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (26,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (27,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (28,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (29,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (30,2,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (1,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (2,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (3,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (4,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (5,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (6,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (7,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (8,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (9,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (10,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (11,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (12,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (13,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (14,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (15,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (16,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (17,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (18,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (19,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (20,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (21,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (22,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (23,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (24,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (25,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (26,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (27,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (28,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (29,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (30,3,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (1,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (2,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (3,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (4,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (5,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (6,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (7,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (8,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (9,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (10,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (11,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (12,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (13,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (14,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (15,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (16,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (17,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (18,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (19,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (20,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (21,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (22,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (23,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (24,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (25,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (26,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (27,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (28,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (29,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (30,4,100);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (1,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (2,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (3,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (4,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (5,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (6,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (7,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (8,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (9,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (10,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (11,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (12,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (13,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (14,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (15,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (16,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (17,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (18,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (19,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (20,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (21,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (22,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (23,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (24,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (25,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (26,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (27,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (28,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (29,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (30,5,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (1,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (2,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (3,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (4,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (5,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (6,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (7,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (8,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (9,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (10,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (11,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (12,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (13,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (14,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (15,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (16,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (17,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (18,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (19,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (20,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (21,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (22,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (23,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (24,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (25,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (26,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (27,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (28,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (29,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (30,6,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (1,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (2,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (3,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (4,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (5,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (6,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (7,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (8,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (9,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (10,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (11,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (12,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (13,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (14,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (15,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (16,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (17,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (18,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (19,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (20,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (21,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (22,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (23,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (24,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (25,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (26,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (27,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (28,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (29,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (30,7,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (1,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (2,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (3,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (4,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (5,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (6,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (7,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (8,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (9,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (10,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (11,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (12,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (13,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (14,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (15,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (16,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (17,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (18,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (19,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (20,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (21,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (22,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (23,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (24,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (25,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (26,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (27,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (28,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (29,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (30,8,60);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (1,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (2,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (3,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (4,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (5,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (6,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (7,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (8,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (9,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (10,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (11,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (12,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (13,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (14,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (15,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (16,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (17,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (18,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (19,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (20,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (21,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (22,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (23,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (24,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (25,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (26,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (27,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (28,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (29,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (30,9,51);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (1,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (2,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (3,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (4,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (5,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (6,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (7,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (8,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (9,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (10,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (11,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (12,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (13,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (14,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (15,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (16,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (17,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (18,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (19,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (20,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (21,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (22,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (23,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (24,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (25,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (26,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (27,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (28,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (29,10,42);
INSERT INTO zav_ishodiPolozeni(ishodID,studentID,postotak) VALUES (30,10,42);

COMMIT;

--updateovi

-- Netko odlucio promijeniti ime
UPDATE zav_profesori SET prezime = 'Posavic' WHERE ime = 'Viseslav' and prezime = 'Knezovic';
UPDATE zav_profesori SET ime = 'Miroslav' WHERE ime = 'Elena' and prezime = 'Pavlic';
UPDATE zav_profesori SET ime = 'Ivo', prezime = 'Sanader' WHERE ime = 'Leopold' and prezime = 'Matanovic';
UPDATE zav_studenti SET prezime = 'Vinkic' WHERE ime = 'Vinko' and prezime = 'Vinkovic';
UPDATE zav_studenti SET ime = 'Cvjetko' WHERE ime = 'Cvjeta' and prezime = 'Martinovic';
UPDATE zav_studenti SET ime = 'Imic', prezime = 'Prezimic' WHERE ime = 'Ilija' and prezime = 'Valentic';
-- netko je otkrio koliko je 99, svima nova lozinka
UPDATE zav_login SET lozinka = 'koliko98';
-- Netko zaboravio lozinku
UPDATE zav_login SET lozinka = '123' WHERE profesorid = 10;
-- Netko htio drugi username
UPDATE zav_login SET korime = 'asek' WHERE studentid = 5;
-- Netko zaboravio svoju lozinku i hoce drugi username
UPDATE zav_login SET korime = 'dumdum', lozinka = 'dumdum' WHERE studentid = 1;
-- Novo ime predmeta
UPDATE zav_predmeti SET ime = 'Kako znati kada pojacati' WHERE id = 9;
-- Zamjena profesora
UPDATE zav_predmeti SET profesorid = 4 WHERE id = 9;
-- Diktatura nastupila
UPDATE zav_predmeti SET profesorid = 4;
-- izmjena imena ishoda
UPDATE zav_ishodi SET ime = 'Kung Fu' where id = 11 and predmetid = 4;
UPDATE zav_ishodi SET ime = 'Moderna oružja' where id = 14;
-- student slucajno podmetnuo 50 eura
UPDATE zav_ishodiPolozeni SET postotak = '100' where studentid = 10;
-- student slucajno nije podmetnuo 50 eura
UPDATE zav_ishodiPolozeni SET postotak = '0' where studentid = 1;
-- svi prosli ishod ;)
UPDATE zav_ishodiPolozeni SET postotak = '99.99' where ishodid = 10;
-- student i dalje slucajno nije podmetnuo 50 eura
UPDATE zav_ishodiPolozeni SET postotak = '49.99' where  ishodid = 10 and studentid = 1;
-- resetirali se ishodi
UPDATE zav_ishodiPolozeni SET postotak = '0' where studentid = 9 and ishodid in (4,5,6);

COMMIT;

-- klasicno brisanje
DELETE FROM zav_ishodiPolozeni where studentid = 2;
DELETE FROM zav_ishodiPolozeni where ishodid in (4,5,6);
DELETE FROM zav_ishodi where predmetid = 2;
DELETE FROM zav_predmeti where profesorid = 2;
DELETE FROM zav_login where profesorid=2 or studentid=2;
DELETE FROM zav_profesori WHERE id=2;
DELETE FROM zav_studenti WHERE id=2;

--potpuno brisanje, moramo paziti na redosljed kao kod dropanja tablica
DELETE FROM zav_ishodiPolozeni;
DELETE FROM zav_ishodi;
DELETE FROM zav_predmeti;
DELETE FROM zav_login;
DELETE FROM zav_profesori;
DELETE FROM zav_studenti;

COMMIT;